"use strict";
var VariantViewer = require("sgd_visualization").VariantViewer;

var vv = new VariantViewer({
	el: document.getElementById("target"),
	config: {
		name: "FAA1",
		strand: "+",
		chromStart: 909343,
		chromEnd: 911445,
		isProteinMode: true,
		proteinLength: 701,
		variantDataProtein: [
			{
				snpType: "",
				start: 175,
				variant_type: "SNP",
				score: 1,
				end: 176
			},
			{
				snpType: "",
				start: 227,
				variant_type: "SNP",
				score: 2,
				end: 228
			},
			{
				snpType: "",
				start: 496,
				variant_type: "SNP",
				score: 1,
				end: 497
			}
		],
		alignedProteinSequences: [
			{
				id: 1,
				name: "S288C",
				href: "http://yeastgenome.org/strain/S288C/overview",
				sequence: "MVAQYTVPVGKAANEHETAPRRNYQCREKPLVRPPNTKCSTVYEFVLECFQKNKNSNAMGWRDVKEIHEESKSVMKKVDGKETSVEKKWMYYELSHYHYNSFDQLTDIMHEIGRGLVKIGLKPNDDDKLHLYAATSHKWMKMFLGAQSQGIPVVTAYDTLGEKGLIHSLVQTGSKAIFTDNSLLPSLIKPVQAAQDVKYIIHFDSISSEDRRQSGKIYQSAHDAINRIKEVRPDIKTFSFDDILKLGKESCNEIDVHPPGKDDLCCIMYTSGSTGEPKGVVLKHSNVVAGVGGASLNVLKFVGNTDRVICFLPLAHIFELVFELLSFYWGACIGYATVKTLTSSSVRNCQGDLQEFKPTIMVGVAAVWETVRKGILNQIDNLPFLTKKIFWTAYNTKLNMQRLHIPGGGALGNLVFKKIRTATGGQLRYLLNGGSPISRDAQEFITNLICPMLIGYGLTETCASTTILDPANFELGVAGDLTGCVTVKLVDVEELGYFAKNNQGEVWITGANVTPEYYKNEEETSQALTSDGWFKTGDIGEWEANGHLKIIDRKKNLVKTMNGEYIALEKLESVYRSNEYVANICVYADQSKTKPVGIIVPNHAPLTKLAKKLGIMEQKDSSINIENYLEDAKLIKAVYSDLLKTGKDQGLVGIELLAGIVFFDGEWTPQNGFVTSAQKLKRKDILNAVKDKVDAVYSSS*"
			},
			{
				id: 3,
				name: "FL100",
				href: "http://yeastgenome.org/strain/FL100/overview",
				sequence: "MVAQYTVPVGKAANEHETAPRRNYQCREKPLVRPPNTKCSTVYEFVLECFQKNKNSNAMGWRDVKEIHEESKSVMKKVDGKETSVEKKWMYYELSHYHYNSFDQLTDIMHEIGRGLVKIGLKPNDDDKLHLYAATSHKWMKMFLGAQSQGIPVVTAYDTLGEKGLIHSLVQTGSRAIFTDNSLLPSLIKPVQAAQDVKYIIHFDSISSEDRRQSGKIYQSAHDAINRIKEVRPDIKTFSFDDILKLGKESCNEIDVHPPGKDDLCCIMYTSGSTGEPKGVVLKHSNVVAGVGGASLNVLKFVGNTDRVICFLPLAHIFELVFELLSFYWGACIGYATVKTLTSSSVRNCQGDLQEFKPTIMVGVAAVWETVRKGILNQIDNLPFLTKKIFWTAYNTKLNMQRLHIPGGGALGNLVFKKIRTATGGQLRYLLNGGSPISRDAQEFITNLICPMLIGYGLTETCASTTILDPANFELGVAGDLTGCVTVKLVDVEELGYFAKNNQGEVWITGANVTPEYYKNEEETSQALTSDGWFKTGDIGEWEANGHLKIIDRKKNLVKTMNGEYIALEKLESVYRSNEYVANICVYADQSKTKPVGIIVPNHAPLTKLAKKLGIMEQKDSSINIENYLEDAKLIKAVYSDLLKTGKDQGLVGIELLAGIVFFDGEWTPQNGFVTSAQKLKRKDILNAVKDKVDAVYSSS*"
			},
			{
				id: 6,
				name: "SK1",
				href: "http://yeastgenome.org/strain/SK1/overview",
				sequence: "MVAQYTVPVGKAANEHETAPRRNYQCREKPLVRPPNTKCSTVYEFVLECFQKNKNSNAMGWRDVKEIHEESKSVMKKVDGKETSVEKKWMYYELSHYHYNSFDQLTDIMHEIGRGLVKIGLKPNDDDKLHLYAATSHKWMKMFLGAQSQGIPVVTAYDTLGEKGLIHSLVQTGSKAIFTDNSLLPSLIKPVQAAQDVKYIIHFDSISSEDRRQSGKIYQSAHDAINKIKEVRPDIKTFSFDDILKLGKESCNEIDVHPPGKDDLCCIMYTSGSTGEPKGVVLKHSNVVAGVGGASLNVLKFVGNTDRVICFLPLAHIFELVFELLSFYWGACIGYATVKTLTSSSVRNCQGDLQEFKPTIMVGVAAVWETVRKGILNQIDNLPFLTKKIFWTAYNTKLNMQRLHIPGGGALGNLVFKKIRTATGGQLRYLLNGGSPISRDAQEFITNLICPMLIGYGLTETCASTTILDPANFELGVAGDLTGCVTVKLVDVEELGYFAKNNQGEVWITGANVTPEYYKNEEETSQALTSDGWFKTGDIGEWEANGHLKIIDRKKNLVKTMNGEYIALEKLESVYRSNEYVANICVYADQSKTKPVGIIVPNHAPLTKLAKKLGIMEQKDSSINIENYLEDAKLIKAVYSDLLKTGKDQGLVGIELLAGIVFFDGEWTPQNGFVTSAQKLKRKDILNAVKDKVDAVYSSS*"
			},
		],
		domains: null,
		
	}
});
